from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        Node(
            package='mission_manager',
            executable='mission_manager',
            name='mission_manager',
            output='screen',
            parameters=[{
                'cmd_vel_topic': '/cmd_vel',
                'mission_control_topic': '/mission_control',
                'mission_state_topic': '/mission_state',
                'target_object_topic': '/target_object',
                'avoid_object_topic': '/avoid_object',
                'avoid_objects_topic': '/avoid_objects',
                'pwm_servo_topic': '/ros_robot_controller/pwm_servo/set_state',
                'bus_servo_topic': '/ros_robot_controller/bus_servo/set_state',
                'timer_rate_hz': 20.0,

                'leave_start_linear_x': 0.08,
                'leave_start_angular_z': 0.0,
                'leave_start_duration_s': 1.5,
                'search_linear_x': 0.06,
                'search_forward_angular_z': 0.10,
                'search_forward_duration_s': 1.4,
                'search_angular_z': 0.35,
                'search_turn_duration_s': 0.9,
                'search_turn_direction': 1.0,
                'search_alternate_turn_direction': False,
                'search_duration_s': 150.0,
                'approach_max_linear_x': 0.10,
                'approach_min_linear_x': 0.03,
                'approach_angular_gain': 0.8,
                'approach_max_angular_z': 0.45,
                'center_tolerance': 0.12,
                'grab_area_ratio': 0.50,
                'target_timeout_s': 0.5,
                'final_forward_linear_x': 0.06,
                'final_forward_duration_s': 1.6,
                'avoid_enabled': True,
                'avoid_timeout_s': 0.5,
                'avoid_area_ratio': 0.45,
                'avoid_center_band': 0.75,
                'avoid_center_corridor': 0.30,
                'avoid_path_margin': 0.30,
                'avoid_emergency_ratio': 0.75,
                'avoid_only_if_closer_than_target': True,
                'avoid_closer_ratio': 1.00,
                'avoid_turn_duration_s': 0.45,
                'avoid_turn_angular_z': 0.50,
                'avoid_forward_duration_s': 0.75,
                'avoid_forward_linear_x': 0.05,
                'avoid_forward_angular_z': 0.18,
                'avoid_turn_direction_sign': 1.0,
                'avoid_vfh_center_weight': 1.5,
                'avoid_vfh_target_weight': 0.60,
                'avoid_vfh_switch_penalty': 0.25,
                'avoid_direction_hold_s': 0.8,
                'avoid_ignore_near_target_enabled': True,
                'avoid_ignore_target_min_y': 0.35,
                'avoid_ignore_target_center_band': 0.25,
                'avoid_ignore_target_x_margin': 0.25,
                'avoid_ignore_target_y_margin': 0.20,
                'reacquire_duration_s': 3.0,
                'reacquire_angular_z': 0.30,
                'back_out_linear_x': -0.08,

                'grab_duration_s': 1.0,
                'back_out_duration_s': 1.5,

                'gripper_enabled': True,
                'gripper_type': 'pwm',
                'gripper_servo_id': 1,
                'gripper_open_position': 1500,
                'gripper_closed_position': 1000,
                'gripper_move_duration_s': 0.5,
            }],
        ),
    ])
